/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.Action;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TelaLogin extends javax.swing.JFrame {

    
    public TelaLogin() {
        initComponents();

    } 
    
    /**
     * Creates new form TelaLogin
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaCadastroUsuario1 = new Telas.TelaCadastroUsuario();
        telaMenu1 = new Telas.TelaMenu();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        pswSenha = new javax.swing.JPasswordField();
        lblPergunta = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(18, 18, 20));
        setIconImages(getIconImages());
        setMinimumSize(new java.awt.Dimension(525, 312));
        getContentPane().setLayout(null);

        btnCadastrar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(189, 147, 249));
        btnCadastrar.setText("Cadastre-se");
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setContentAreaFilled(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(20, 190, 190, 40);

        btnEntrar.setBackground(new java.awt.Color(4, 211, 97));
        btnEntrar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(null);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(280, 180, 192, 50);

        lblSenha.setBackground(new java.awt.Color(0, 0, 0));
        lblSenha.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha: ");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(20, 80, 100, 40);

        lblUsuario.setBackground(new java.awt.Color(0, 0, 255));
        lblUsuario.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuário: ");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(20, 20, 100, 40);

        pswSenha.setBackground(new java.awt.Color(18, 18, 20));
        pswSenha.setForeground(new java.awt.Color(255, 255, 255));
        pswSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pswSenha.setBorder(null);
        pswSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswSenhaFocusLost(evt);
            }
        });
        pswSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(pswSenha);
        pswSenha.setBounds(120, 80, 210, 40);

        lblPergunta.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lblPergunta.setForeground(new java.awt.Color(255, 255, 255));
        lblPergunta.setText("Não está cadastrado?");
        getContentPane().add(lblPergunta);
        lblPergunta.setBounds(40, 180, 170, 18);

        txtUsuario.setBackground(new java.awt.Color(18, 18, 20));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setBorder(null);
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(120, 20, 210, 40);

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1024px-Black_flag.svg.png"))); // NOI18N
        getContentPane().add(lblIcon);
        lblIcon.setBounds(-20, -30, 580, 440);

        setSize(new java.awt.Dimension(532, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        TelaCadastroUsuario tCadastro;
        tCadastro = new TelaCadastroUsuario();
        tCadastro.setVisible(true);
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        
        if (txtUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o nome de usuario");
            txtUsuario.requestFocus();
            return;
        }
        
        if (pswSenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha a senha");
            pswSenha.requestFocus();
            return;
        
        }
        
        
        try {
            Connection conexao;
            PreparedStatement st;
            ResultSet resultado;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/bancoPadaria", "root", "b9310u54");
            st = conexao.prepareStatement("SELECT * from usuarios WHERE usuario=? AND senha=?");
            st.setString(1, txtUsuario.getText());
            st.setString(2, pswSenha.getText());
            resultado = st.executeQuery();
            if (resultado.next()) {
                txtUsuario.setText("");
                pswSenha.setText("");
                TelaMenu telaMenu; 
                telaMenu = new TelaMenu(resultado.getString("usuario"), resultado.getString("cargo"));
                telaMenu.setVisible(true);
               
            } else {
                JOptionPane.showMessageDialog(null, "Usuario e/ou senha inválidos");
                txtUsuario.requestFocus();
            }


        } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Você não tem o driver na biblioteca");
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Algum parâmetro do BD está incorreto");
        }
                                    
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void pswSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenhaActionPerformed

    }//GEN-LAST:event_pswSenhaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void pswSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswSenhaFocusGained
        pswSenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(99, 59, 188), new java.awt.Color(99, 59, 188), new java.awt.Color(99, 59, 188), new java.awt.Color(99, 59, 188)));
        
        
    }//GEN-LAST:event_pswSenhaFocusGained

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        txtUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(99, 59, 188), new java.awt.Color(99, 59, 188), new java.awt.Color(99, 59, 188), new java.awt.Color(99, 59, 188)));
        
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        txtUsuario.setBorder(null);
        
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void pswSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswSenhaFocusLost
        pswSenha.setBorder(null);
    }//GEN-LAST:event_pswSenhaFocusLost

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pswSenha;
    private Telas.TelaCadastroUsuario telaCadastroUsuario1;
    private Telas.TelaMenu telaMenu1;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
